version: "3.5"

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - psql_data:/var/lib/postgresql/data
  app:
    build: .
    container_name: app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
volumes:
  psql_data:
